phrase:
  
  project_id: 40642ac6a1936acc0e0ac2cf1798a80f
  push:
    sources:
    - file: ./4github.json
      params:
        file_format: simple_json
        locale_id: en
        tags: github
        update_translations: true
        autotranslate: true
        
  pull:
    targets:
    - file: ./4github-de.json
      params:
        file_format: simple_json
        locale_id: de
        tags: github
